fix $ip not used, must force ip v4

diff --git a/hasrv b/hasrv
--- a/hasrv
+++ b/hasrv
@@ -26,12 +26,12 @@ EOF
 
 function try_connect
 {
-    typeset host=$1 port=$2 timeout=${3:-2} ip=$(getent hosts $host)
+    typeset host=$1 port=$2 timeout=${3:-2} ip=$(getent ahostsv4 $host)
     # resolve ip as /dev/tcp does not seem to use multiple dns servers configured
-    [ ! "$ip" ] && echo "Cannot resolve host $host" >&2 && return 1
+    [ ! "$ip" ] && echo "Warn: Cannot resolve host $host" >&2 && return 1
     echo "$ip" |read ip _
-    timeout $timeout ksh -c "echo > /dev/tcp/$1/$2" >/dev/null 2>&1 && return 0
-    echo "Cannot connect to $host ($ip) on port $port" >&2
+    timeout $timeout ksh -c "echo > /dev/tcp/$ip/$port" >/dev/null 2>&1 && return 0
+    echo "Warn: Cannot connect to $host ($ip) on port $port" >&2
     return 1
 }
 
